apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojo
  labels:
    app: gojo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gojo
  template:
    metadata:
      labels:
        app: gojo
    spec:
      containers:
      - name: gojo
        image: chirag117/gojo:v1
        ports:
        - containerPort: 8070
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8070
          initialDelaySeconds: 5
          periodSeconds: 10